name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    env:
      ADMIN_PROJECT: BioEngine.Admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Install node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '15'
          cache: 'npm'
          cache-dependency-path: |
            src/${{ env.ADMIN_PROJECT }}/Web/package.json
      - name: Build admin js
        working-directory: src/${{ env.ADMIN_PROJECT }}/Web
        shell: bash
        run: |
          npm ci
          npm run prod
      - name: Publish admin
        run: dotnet publish src/${{ env.ADMIN_PROJECT }}/${{ env.ADMIN_PROJECT }}.csproj -o /app/ -c Release
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build admin image
        uses: docker/build-push-action@v2
        with:
          file: ./src/${{ env.ADMIN_PROJECT }}/Dockerfile
          context: /app
          push: false
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

