name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: ghcr.io/sitkoru/actions-container
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

